index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        # make a permanent redirection...
        permanent: true
        # ...and keep the original query string parameters
        keepQueryParams: true
admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        # make a permanent redirection...
        permanent: true
        # ...and keep the original query string parameters
        keepQueryParams: true

dashboard:
    controller: App\Controller\DashboardController:index
    path: /dashboard

dashboard_admin:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /gestionaire
    type: annotation

user_registration:
    path: /register
    defaults: { _controller: App\Controller\RegistrationController:registerAction }

agenda:
    path: /agenda
    defaults: { _controller: App\Controller\AgendaController:index }